server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
    username: root
    password: root+123
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#      show-sql: true


logging:
  config: classpath:logback-spring.xml
  level:
    my.project: trace

#jwt:
#  tokenHeader: Authorization
#  secret: piteam+70771579
#  expiration: 28800
#  tokenHead: 'Bearer'

bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
    tokenHead: 'Bearer '

secure:
  ignored:
    urls: #url白名單
      - /api/auth/signing
      - /api/auth/signup
      - /api/test/
      - /actuator/health
      - /actuator/prometheus
      - /admin/login
      - /admin/register
