server:
  port: 8080

spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
  type:
    descriptor:
      sql:
        BasicBinder: TRACE
  profiles:
    active: dev

jwt:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
    tokenHead: 'Bearer '

secure:
  ignored:
    urls: #url白名單
      - /api/auth/signing
      - /api/auth/signup
      - /api/test/
      - /swagger-ui/index.html
      - /actuator/health
      - /actuator/prometheus
      - /admin/login
